name: Java Version Exporter Test
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - uses: joshlong/java-version-exporter@v10
        id: jve

      - name: Test
        env:
          V: ${{ steps.jve.outputs.java_major_version }}
        run: |
          echo $V
