name: Maven Property Evaulator Test
on:
  repository_dispatch:
    types: [test-event]
  create:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: joshlong/java-version-exporter@v2
      - name: Test
        run: |
          echo "JAVA_VERSION: ${"JAVA_VERSION:no version environment variable}"
          echo "JAVA_VERSION: ${"JAVA_MAJOR_VERSION:no major version environment variable}"
