name: Java Version Exporter Test
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: joshlong/java-version-export-github-action@v17
        id: jve

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ steps.jve.outputs.java_major_version }}

      - run: java --version
