name: Maven Property Evaulator Test
on:
  repository_dispatch:
    types: [test-event]
  create:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bootiful-podcast/bp-mode-github-action@v34
      - name: Test
        run: |
          # export PATH=$GITHUB_WORKSPACE/bin/:$PATH
          echo "MAVEN EXPRESSION: ${MAVEN_EXPRESSION}"
